### PR TITLE
added week total for every week

### PR DESCRIPTION
**Pull request by Loscho19**
Position styling und bennenung war schwierig.

### CODE REVIEW

**Review by matthiask — CHANGES_REQUESTED** [review]
Makes sense! There's a much shorter way to do this.

The interface doesn't support showing future days, `week_end` isn't necessary.

So, `show_this_week = dt.date.today() >= monday()` (using monday from `workbench.tools.validation`)

The sum of this week's hours are available as `user.hours["week"]` already, see https://github.com/matthiask/workbench/blob/189d4479d445a81a55dfd8a9583938504108fe06/workbench/accounts/models.py#L223-L236

So, I'd add `is_this_week` or `show_this_week` to the template context and use `{{ request.user.hours.week|hours }}` in the template.

Dankeschön :)

**Review by matthiask — COMMENTED** [review]
Ah sorry, für *jede* Woche. Ich schau nochmals drüber.

**Comment by matthiask** [comment]
Nebenbei: Kennst Du https://workbench.feinheit.ch/users/169/statistics/ ? Ist oben rechts verlinkt im User-Menü.

Merci!

**Comment by Loscho19** [comment]
> Nebenbei: Kennst Du https://workbench.feinheit.ch/users/169/statistics/ ? Ist oben rechts verlinkt im User-Menü.
> 
> Merci!

Tatsächlich noch nie gesehen das die Stunden da ja stehen

**Pull request merged**
